apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-game-deployment
  labels:
    app: mario-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario-game
  template:
    metadata:
      labels:
        app: mario-game
    spec:
      containers:
      - name: mario-game-container
        image: bijannandi2025/myfirst_code:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
