apiVersion: v1
kind: Service
metadata:
  name: mario-game-service
spec:
  type: NodePort
  selector:
    app: mario-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Accessible on http://localhost:30007
